In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("athlete_events.csv")

In [3]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [4]:
#Create a table grouped by Team, Year, and Medal to get medal counts.
countrygroupdf = df.groupby(["Team","Year","Medal"]).size()

In [5]:
countrygroupdf.head(50)

Team                          Year  Medal
A North American Team         1900  Bronze     4
Afghanistan                   2008  Bronze     1
                              2012  Bronze     1
Algeria                       1984  Bronze     2
                              1992  Bronze     1
                                    Gold       1
                              1996  Bronze     1
                                    Gold       2
                              2000  Bronze     3
                                    Gold       1
                                    Silver     1
                              2008  Bronze     1
                                    Silver     1
                              2012  Gold       1
                              2016  Silver     2
Ali-Baba II                   1948  Bronze     5
Amateur Athletic Association  1900  Gold       5
Amstel Amsterdam              1908  Bronze     4
Ancora                        1920  Gold       4
Angelita                      1932  Gold      12
Antwerpia V                   1920  Bronze     5
Aphrodite                     1964  Bronze     3
Argentina                     1924  Bronze     2
                                    Gold       5
                                    Silver     3
                              1928  Bronze     5
                                    Gold       3
                                    Silver    18
                              1932  Gold       3
                                    Silver     1
                              1936  Bronze     4
                                    Gold       5
                                    Silver     2
                              1948  Bronze     1
                                    Gold       3
                                    Silver     2
                              1952  Bronze     2
                                    Gold       2
                                    Silver     2
                              1956  Bronze     1
                                    Silver     1
                              1960  Bronze     1
                              1964  Silver     1
                              1968  Bronze     2
                              1972  Silver     1
                              1988  Bronze    12
                                    Silver     1
                              1992  Bronze     2
                              1996  Bronze     1
                                    Silver    19
dtype: int64

In [6]:
countrydf = pd.DataFrame(countrygroupdf).reset_index()

In [7]:
countrydf.head()

                    Team  Year   Medal  0
0  A North American Team  1900  Bronze  4
1            Afghanistan  2008  Bronze  1
2            Afghanistan  2012  Bronze  1
3                Algeria  1984  Bronze  2
4                Algeria  1992  Bronze  1

In [8]:
medalcountdf = countrydf.rename(columns={0:"Medal_Count"})

In [9]:
#Create a table grouped by Team, Year, and Medal to get medal counts.
namegroupdf = df.groupby(["Name","Sex","Team","Sport","Medal"]).size()

In [10]:
namedf = pd.DataFrame(namegroupdf).reset_index()

In [11]:
namedf.head()

,Name,Sex,Team,Sport,Medal,0
0,A. Albert,M,Union des Socits Franais de Sports Athletiques,Rugby,Gold,1
1,A. Dubois,M,Gitana-2,Sailing,Bronze,1
2,A. Dubois,M,Gitana-2,Sailing,Silver,1
3,"A. Joshua ""Josh"" West",M,Great Britain,Rowing,Silver,1
4,A. Lawry,M,Cornwall,Rugby,Silver,1

In [12]:
goldathletes = namedf[namedf["Medal"] == "Gold"].reset_index()

del goldathletes["index"]
goldathletesdf = goldathletes.rename(columns={0:"Medal_Count"})

goldathletesdf.sort_values(by=["Medal_Count"], ascending=False)

,Name,Sex,Team,Sport,Medal,Medal_Count
6741,"Michael Fred Phelps, II",M,United States,Swimming,Gold,23
7958,"Raymond Clarence ""Ray"" Ewry",M,United States,Athletics,Gold,10
7501,Paavo Johannes Nurmi,M,Finland,Athletics,Gold,9
5680,Larysa Semenivna Latynina (Diriy-),F,Soviet Union,Gymnastics,Gold,9
6440,Mark Andrew Spitz,M,United States,Swimming,Gold,9
2979,"Frederick Carlton ""Carl"" Lewis",M,United States,Athletics,Gold,9
9477,Usain St. Leo Bolt,M,Jamaica,Athletics,Gold,8
6594,"Matthew Nicholas ""Matt"" Biondi",M,United States,Swimming,Gold,8
4564,"Jennifer Elisabeth ""Jenny"" Thompson (-Cumpelik)",F,United States,Swimming,Gold,8
8508,Sawao Kato,M,Japan,Gymnastics,Gold,8
7333,Ole Einar Bjrndalen,M,Norway,Biathlon,Gold,8
1192,Borys Anfiyanovych Shakhlin,M,Soviet Union,Gymnastics,Gold,7
2195,"Donald Arthur ""Don"" Schollander",M,United States,Swimming,Gold,7
89,Aladr Gerevich (-Gerei),M,Hungary,Fencing,Gold,7
7210,Nikolay Yefimovich Andrianov,M,Soviet Union,Gymnastics,Gold,7
9667,Viktor Ivanovych Chukarin,M,Soviet Union,Gymnastics,Gold,7
9834,Vra slavsk (-Odloilov),F,Czechoslovakia,Gymnastics,Gold,7
5568,Kristin Otto,F,East Germany,Swimming,Gold,6
6339,Maria Valentina Vezzali,F,Italy,Fencing,Gold,6
87,Akinori Nakayama,M,Japan,Gymnastics,Gold,6
423,Allyson Michelle Felix,F,United States,Athletics,Gold,6
466,Amy Deloris Van Dyken (-Rouen),F,United States,Swimming,Gold,6
3263,Gert Fridolf Fredriksson,M,Sweden,Canoeing,Gold,6
1691,"Christopher Andrew ""Chris"" Hoy",M,Great Britain,Cycling,Gold,6
2314,Edoardo Mangiarotti,M,Italy,Fencing,Gold,6
9737,Vitaly Venediktovich Shcherbo,M,Unified Team,Gymnastics,Gold,6
7107,Nedo Nadi,M,Italy,Fencing,Gold,6
4467,Jason Francis Kenny,M,Great Britain,Cycling,Gold,6
8362,Rudolf Krpti,M,Hungary,Fencing,Gold,6
3241,Gerard Theodor Hubert Van Innis,M,Belgium,Archery,Gold,6
...,...,...,...,...,...,...
3881,Herbert Krug,M,West Germany,Equestrianism,Gold,1
3882,"Herbert Philip ""Bert"" Williams",M,Kathleen,Sailing,Gold,1
3883,"Herbert Roger ""Herb"" Morris",M,United States,Rowing,Gold,1
3884,Herbert Roper Barrett,M,Great Britain-1,Tennis,Gold,1
3885,Herbert Runge,M,Germany,Boxing,Gold,1
3886,Herbert Smith,M,Great Britain,Football,Gold,1
3887,Herbert Spencer Perry,M,Great Britain,Shooting,Gold,1
3888,"Herma Planck-Szabo (-Jarosz, -Stark)",F,Austria,Figure Skating,Gold,1
3889,Herman Andreas Nyberg,M,Kitty-1,Sailing,Gold,1
3891,Herman Georges Berger,M,France,Fencing,Gold,1
3892,"Herman Matinpoika ""Hermanni"" Pihlajamki",M,Finland,Wrestling,Gold,1
3876,Herbert Adamski,M,Germany,Rowing,Gold,1
3875,Heorhiy Vadymovych Pohosov,M,Unified Team,Fencing,Gold,1
3874,Henry Wittenberg,M,United States,Wrestling,Gold,1
3859,Henry Marvin Bailey,M,United States,Shooting,Gold,1
3853,Henry George,M,Belgium,Cycling,Gold,1
3854,"Henry Jean Guy ""Jean-Guy"" Gautier",M,Union des Socits Franais de Sports Athletiques,Rugby,Gold,1
3855,"Henry John ""Harry"" Spanjer",M,United States,Boxing,Gold,1
3856,"Henry Kent Mitchell, II",M,United States,Rowing,Gold,1
3857,Henry Louis Scott,M,United States,Athletics,Gold,1
3858,Henry Maitland Macintosh,M,Great Britain,Athletics,Gold,1
3860,Henry Maske,M,East Germany,Boxing,Gold,1
3871,Henry Treise Morshead,M,Great Britain,Alpinism,Gold,1
3862,"Henry Morton ""Harry"" Llewellyn",M,Great Britain,Equestrianism,Gold,1
3863,Henry North Haslam,M,Upton Park FC,Football,Gold,1
3864,"Henry Norwood ""Barney"" Ewell",M,United States,Athletics,Gold,1
3867,Henry Seiling,M,Milwaukee Athletic Club-1,Tug-Of-War,Gold,1
3868,"Henry Stoddard ""Harry"" Babcock",M,United States,Athletics,Gold,1
3870,"Henry Thomas ""Harry"" Blackstaffe",M,Great Britain,Rowing,Gold,1
10574,ystein Pettersen,M,Norway,Cross Country Skiing,Gold,1

In [13]:
silverathletes = namedf[namedf["Medal"] == "Silver"].reset_index()

del silverathletes["index"]
silverathletesdf = silverathletes.rename(columns={0:"Medal_Count"})

silverathletesdf.sort_values(by=["Medal_Count"], ascending=False)

silverathletesdf.to_csv("silverathletes.csv")

,Name,Sex,Team,Sport,Medal,Medal_Count
232,Aleksandr Nikolayevich Dityatin,M,Soviet Union,Gymnastics,Silver,6
9590,Shirley Frances Babashoff,F,United States,Swimming,Silver,6
11171,Yang Yang,F,China,Short Track Speed Skating,Silver,6
7539,Mikhail Yakovlevich Voronin,M,Soviet Union,Gymnastics,Silver,6
8718,Raisa Petrovna Smetanina,F,Soviet Union,Cross Country Skiing,Silver,5
3733,Gustavo Marzi,M,Italy,Fencing,Silver,5
6368,Leisel Marie Jones,F,Australia,Swimming,Silver,5
11451,Zoltn Imre dn von Halmay,M,Hungary,Swimming,Silver,5
2437,Edoardo Mangiarotti,M,Italy,Fencing,Silver,5
7926,Nikolay Yefimovich Andrianov,M,Soviet Union,Gymnastics,Silver,5
6243,Larysa Semenivna Latynina (Diriy-),F,Soviet Union,Gymnastics,Silver,5
11370,Yury Yevlampiyevich Titov,M,Soviet Union,Gymnastics,Silver,5
5796,Katalin Kovcs,F,Hungary,Canoeing,Silver,5
1948,Dagmar Hase,F,Germany,Swimming,Silver,5
572,Andrea Ehrig-Schne-Mitscherlich,F,East Germany,Speed Skating,Silver,5
10647,Viktor Nikitovich Lisitsky,M,Soviet Union,Gymnastics,Silver,5
7080,Mariya Kindrativna Horokhovska,F,Soviet Union,Gymnastics,Silver,5
2143,Dawn Lorraine Fraser,F,Australia,Swimming,Silver,4
5684,Kara Lynn Joyce,F,United States,Swimming,Silver,4
9933,Svetlana Vasilyevna Khorkina,F,Russia,Gymnastics,Silver,4
10424,"Ursula ""Uschi"" Disl",F,Germany,Biathlon,Silver,4
9873,"Susan ""Susie"" O'Neill",F,Australia,Swimming,Silver,4
4514,Isabelle Regina Werth,F,Germany,Equestrianism,Silver,4
9124,Roger Franois Ducret,M,France,Fencing,Silver,4
7754,Natalie Anne Coughlin (-Hall),F,United States,Swimming,Silver,4
1469,Carl Townsend Osburn,M,United States,Shooting,Silver,4
2753,Erika Zuchold (Barth-),F,East Germany,Gymnastics,Silver,4
3714,Gustaf Vilhelm Carlberg,M,Sweden,Shooting,Silver,4
5809,Kateina Neumannov,F,Czech Republic,Cross Country Skiing,Silver,4
7520,Miho Takeda,F,Japan,Synchronized Swimming,Silver,4
...,...,...,...,...,...,...
4097,Henrik Olof Stenson,M,Sweden,Golf,Silver,1
4098,Henry Anton Homburger,M,United States-2,Bobsleigh,Silver,1
4099,Henry Chandler Egan,M,United States,Golf,Silver,1
4100,Henry Charles Boucha,M,United States,Ice Hockey,Silver,1
4101,Henry Crawford Palmer,M,France,Basketball,Silver,1
4102,Henry George Burr,M,Great Britain,Shooting,Silver,1
4103,Henry Gustaves Kaltenbrunn,M,South Africa,Cycling,Silver,1
4104,Henry Johan Johansson,M,Sweden,Ice Hockey,Silver,1
4086,Henri Rang,M,Romania,Equestrianism,Silver,1
4084,Henri Marie Raoul Gaillard de Saint Germain,M,France,Fencing,Silver,1
4062,"Henning Johannes ""Henry"" Dafel",M,South Africa,Athletics,Silver,1
4083,Henri Louis Rmi Alexandre Thophile Quersin,M,Belgium,Shooting,Silver,1
4063,Henning Lynge Jakobsen,M,Denmark,Canoeing,Silver,1
4064,Henning Lynggaard Enoksen,M,Denmark,Football,Silver,1
4066,Henri Alexis Tauzin,M,France,Athletics,Silver,1
4067,Henri Baur,M,Austria,Wrestling,Silver,1
4068,Henri Camille Praux,M,France,Rowing,Silver,1
4070,Henri Cohen,M,Brussels Swimming and Water Polo Club,Water Polo,Silver,1
4071,Henri Galau,M,France,Rugby,Silver,1
4072,Henri Hyacinthe Helle,M,France,Archery,Silver,1
4073,Henri Jean Cochet,M,France,Tennis,Silver,1
4074,Henri Jean Cochet,M,France-1,Tennis,Silver,1
4075,"Henri Jean Joseph ""Harry"" Derckx",M,Netherlands,Hockey,Silver,1
4076,Henri Jean LaBorde,M,United States,Athletics,Silver,1
4077,Henri Joly,M,Smyrna,Football,Silver,1
4078,Henri Joseph Gedein Laame,M,Belgium,Equestrianism,Silver,1
4079,Henri Jules Valton,M,Crabe II-1,Sailing,Silver,1
4081,Henri Louis Dsir Mouillefarine,M,France,Cycling,Silver,1
4082,Henri Louis Marie van Schaik,M,Netherlands,Equestrianism,Silver,1
11551,va Szkely (-Gyarmati),F,Hungary,Swimming,Silver,1

In [ ]:
bronzeathletes = namedf[namedf["Medal"] == "Bronze"].reset_index()

del bronzeathletes["index"]
bronzeathletesdf = bronzeathletes.rename(columns={0:"Medal_Count"})

bronzeathletesdf.sort_values(by=["Medal_Count"], ascending=False)

bronzeathletesdf.to_csv("bronzeathletes.csv")